;   PDS Remake
;   https://github.com/diyelectromusic/PDS_Remake
;
;   Edited version for use with an online assembler to bootstrap a PDS.
;   Full details here: https://emalliab.wordpress.com/2026/07/10/pds-the-programmers-development-system-part-6/
;
;  ------------------------------------------------------------------------------------
;
;   The short PDS download software for the ZX-SPECTRUM
;
;It is as short as possible, and can only be used for assembling and
;downloading. Some monitor commands that only download will also work.
;It may be situated anywhere in memory. Note that it uses up two bytes
;of stack space, it uses the Sinclair stack, setup at the top of memory
;or where ever you do a CLEAR. It disables the interupts, so you may
;download over the system variables at 5C00h upwards.
;
; The code is exactly 102 bytes long
;
;When you first run the download software you should jump to label START,
;if you intend to enter it again then you should jump to MAINLOOP as it will
;already be setup correctly.
;
; Setup this ORG to point where you want the download software to be in
; memory. Note that this program as is, requires eight bytes before this
; address for a small 'return to basic program'
;
	ORG 8000H	;This could go anywhere (best in fast memory >8000h)
;
STARTL:	DI
	LD A,255
	OUT (127),A
	OUT (63),A
	LD A,63
	OUT (127),A
	LD A,255
	OUT (95),A	;Setup the direction of the IO ports
	OUT (95),A
	LD D,64	;Setup flags - Input from main computer
;
; Main loop
;
MAINLOOP:	CALL GETBYTE	;Get 'command byte'
	LD A,E
	CP 180	;Download code into aabb, len=ccdd
	JP Z,DLOAD
	CP 183	;Select bank aa
	JP Z,SBANK
	CP 181	;Execute code from aabb?
	JP NZ,MAINLOOP	;Not recognised - keep looping.
;
; Function 181, Execute code from aabb
;
	CALL GETBYTE
	LD H,E	;Get address of routine
	CALL GETBYTE
	LD L,E
	LD BC,MAINLOOP
	PUSH BC	;Put return address on stack and jump to routine
	JP (HL)
;
; Function 180, Download code into aaaa, length=bbbb
;
DLOAD:	CALL GETBYTE
	LD H,E
	CALL GETBYTE
	LD L,E	;Get start address
	CALL GETBYTE
	LD B,E
	CALL GETBYTE
	LD C,E	;Get length of code
;
DLOAD1:	CALL GETBYTE
	LD (HL),E	;Get bytes and store in RAM
	INC HL
	DEC BC
	LD A,B	;Keep getting bytes
	OR C
	JP NZ,DLOAD1
	JR MAINLOOP	;Go back into main download loop
;
; Function 183, select bank xx (This is different for each target computer)
;
SBANK:	CALL GETBYTE
	LD BC,7FFDH	;HL, BC and A may be corrupted here
	OUT (C),E	;This will change banks on the speccy '128
	JR MAINLOOP	;E is the bank data byte, D is not to be used!
;
; Get a byte from the main computer into E
;
GETBYTE:	IN A,(63)
	XOR D
	RRCA
	JP C,GETBYTE	;Wait for 'I've sent the byte'
	IN A,(31)
	LD E,A	;Get the byte into the E register
	LD A,D
	OUT (63),A	;Say 'I've got it!'
	XOR 129
	LD D,A	;Flip flags for next byte
	RET
;
;
;
;
;
;
;
; End of the download software, now a small program to set the top of memory
; one byte below the download software, then reset the spectrum and return
; to basic so you may save out the download software using the following
; basic loader :
;
; 1 LOAD "" CODE:RANDOMISE USR start address
;
; Save this using either :
;
; SAVE "DLOADER" LINE 1 : SAVE "CODE" CODE startaddress,102
;
; or for microdrives :
;
; SAVE *"m";1;"DLOADER" LINE 1 :  SAVE *"m";1;"CODE" CODE startaddress,102
;
;
	;ORG START-8	;Put before download (so gets overwritten)
	;EXEC $	;Execute code from here
	;DI
	;LD DE,START-1	;Where 'top of memory' will be
	;XOR A
	;JP 11CBH	;Reset Spectrum, leaving download software
;
;
;
	;SEND COMPUTER1
	;END
